# Generated by Django 4.2.20 on 2025-04-18 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_reference_count'),
    ]

    operations = [
    ]
